name: 67p_swarm
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy==1.23.5
  - pygmo
  - polyhedral-gravity-model
  - pyvista
  - matplotlib
  - panel
  - jupyter_backend
  - pykep
  - pyquaternion
  - dotmap
  - pip:
      - tetgen
      - desolver